spring.application.name=user-service
spring.profiles.active=develop
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
logging.level.com.example.user_service=INFO
logging.level.root=INFO
spring.redis.host.port=6379
jwt.secret=A9fK3pL2Zx8QWmR7E4TnYH5VJcD6S0U1
threadpool.maxPoolSize=200
threadpool.corePoolSize=100
threadpool.queueCapacity=200
springdoc.enable-spring-security=false





